SyntaxError: invalid syntax (947603589.py, line 1)

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [15]:
# Exp 1- 8 as per executed in labs Inputs will be varied practicals hard coded , some with tensorflow and keras CNN, rnn, autoencoder and backpropogation can be implemented on datasets mostly mnist, iris, catand dog Sometimes u need to take inputs of dataset by creating shapes So there are variations while taking inputs Instructions while coming to the lab.

## Experiment 1

In [34]:
# Experiment 1: Perceptron Learning Algorithm

def bipolar(x):
    if x > 0:
        return 1
    elif x == 0:
        return 0
    else:
        return -1

def unipolar(net):
    if net < 0:
        return 0
    else:
        return 1

def process(x, d, w1, w2, b, activation, delta_b, c=1):
    net = w1*x[0] + w2*x[1] + b
    fnet = activation(net)
    error = d - fnet
    del_w1 = c * error * x[0]
    del_w2 = c * error * x[1]
    del_b = error
    delta_b.append(del_b)
    w1 += del_w1
    w2 += del_w2
    b += del_b
    return w1, w2, b, delta_b

x = [[0, 0], 
     [1, 0],
     [0, 1],
     [1, 1]]
d = [0, 0, 0, 1]
w1, w2, b = 0, 0, 0
epoch = 0
delta_b = []
while delta_b != [0, 0, 0, 0]:
    epoch += 1
    delta_b = []
    for i in range(len(x)):
        w1, w2, b, delta_b = process(x[i], d[i], w1, w2, b, unipolar, delta_b)

    print("Epoch: ", epoch, "Delta_b: ", delta_b, "Final Weights: ", [w1, w2], "Final Bias: ", b)

Epoch:  1 Delta_b:  [-1, 0, 0, 1] Final Weights:  [1, 1] Final Bias:  0
Epoch:  2 Delta_b:  [-1, -1, 0, 1] Final Weights:  [1, 2] Final Bias:  -1
Epoch:  3 Delta_b:  [0, -1, -1, 1] Final Weights:  [1, 2] Final Bias:  -2
Epoch:  4 Delta_b:  [0, 0, -1, 1] Final Weights:  [2, 2] Final Bias:  -2
Epoch:  5 Delta_b:  [0, -1, 0, 0] Final Weights:  [1, 2] Final Bias:  -3
Epoch:  6 Delta_b:  [0, 0, 0, 0] Final Weights:  [1, 2] Final Bias:  -3


## Experiment 2

In [ ]:
# Experiment 2: Packpropagation Algorithm
# Forward and Backward Pass

# 0 - 0 - 0
# 0 - 0 - 0

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward_pass(input, weight, bias, activation):
    layer = np.dot(weight, input) + bias
    return float(activation(layer)[0])

def error_calculation(excepted_output, output):
    return 0.5 * np.sum((excepted_output - output) ** 2)

def update_weights_inner(output, target, hidden, input, weight_affecting, weight_i, learning_rate):
    error_i_1 = (output[0] - target[0]) * (output[0] * (1 - output[0])) * weight_affecting[0] * (hidden[0] * (1 - hidden[0])) * input
    error_i_2 = (output[1] - target[1]) * (output[1] * (1 - output[1])) * weight_affecting[1] * (hidden[0] * (1 - hidden[0])) * input
    error_i = error_i_1 + error_i_2
    weight = weight_i - learning_rate * error_i
    return weight

def update_weights_outer(output, target, input, weight_i, learning_rate):
    error_i = (output - target) * (output * (1 - output)) * input
    weight = weight_i - learning_rate * error_i
    return weight

def backward_pass(weights, biases, inputs, hidden, excepted_output, output):
    w5 = update_weights_outer(output[0], excepted_output[0], hidden[0], weights[4], 0.6)
    w6 = update_weights_outer(output[0], excepted_output[0], hidden[1], weights[5], 0.6)
    w7 = update_weights_outer(output[1], excepted_output[1], hidden[1], weights[6], 0.6)
    w8 = update_weights_outer(output[0], excepted_output[0], hidden[1], weights[7], 0.6)

    w1 = update_weights_inner(output, excepted_output, hidden, inputs[0], [weights[4], weights[6]], weights[0], 0.6)
    w2 = update_weights_inner(output, excepted_output, hidden, inputs[1], [weights[5], weights[7]], weights[2], 0.6)
    w3 = update_weights_inner(output, excepted_output, hidden, inputs[0], [weights[4], weights[6]], weights[1], 0.6)
    w4 = update_weights_inner(output, excepted_output, hidden, inputs[1], [weights[5], weights[7]], weights[3], 0.6)

    return np.array([w1, w2, w3, w4, w5, w6, w7, w8])

inputs = [0.1, 0.5]
weights = [0.1, 0.3, 0.2, 0.4 , 0.5, 0.6, 0.7, 0.8]
biases = [0.25, 0.25, 0.35, 0.35]
excepted_output = [0.05, 0.95]

hidden_network1 = forward_pass(inputs, weights[:2], biases[:1], sigmoid)
hidden_network2 = forward_pass(inputs, weights[2:4], biases[1:2], sigmoid)
hidden = [hidden_network1, hidden_network2]
output_network1 = forward_pass(hidden, weights[4:6], biases[2:3], sigmoid)
output_network2 = forward_pass(hidden, weights[6:8], biases[3:4], sigmoid)
output = [output_network1, output_network2]

error = error_calculation(np.array(excepted_output), np.array(output))

# updated_weights = backward_pass(weights, biases, inputs, hidden, excepted_output, output)
# print("Updated Weights: ", updated_weights)

epochs = 47000

for i in range(epochs):
    hidden_network1 = forward_pass(inputs, weights[:2], biases[:1], sigmoid)
    hidden_network2 = forward_pass(inputs, weights[2:4], biases[1:2], sigmoid)
    hidden = [hidden_network1, hidden_network2]
    output_network1 = forward_pass(hidden, weights[4:6], biases[2:3], sigmoid)
    output_network2 = forward_pass(hidden, weights[6:8], biases[3:4], sigmoid)
    output = [output_network1, output_network2]

    error = error_calculation(np.array(excepted_output), np.array(output))

    updated_weights = backward_pass(updated_weights, biases, inputs, hidden, excepted_output, output)
    weights = updated_weights
    if i % 100 == 0:
        print(f"Epoch {i}: Error: {error}")
    if error < 0.01:
        break
print("Final Output: ", output)
print("Final Weights: ", weights)
print("Final Error: ", error)



## Experiment 3

In [ ]:
# Experiment 3: CNN

def convolve2d(image, kernel, stride):
    kernel_height, kernel_width = kernel.shape
    image_height, image_width = image.shape
    output_height = (image_height - kernel_height) // stride + 1
    output_width = (image_width - kernel_width) // stride + 1
    new_image = np.zeros((output_height, output_width)).astype(np.int32)
    for x in range(0, output_width):
        for y in range(0, output_height):
            new_image[y][x] = np.sum(image[y * stride:y * stride + kernel_height, x * stride:x * stride + kernel_width] * kernel).astype(np.int32)
    return new_image

def maxpooling(input, pool_size, stride):
    input_height, input_width = input.shape
    output_height = (input_height - pool_size) // stride + 1
    output_width = (input_width - pool_size) // stride + 1
    new_image = np.zeros((output_height, output_width)).astype(np.int32)
    for i in range(output_height):
        for j in range(output_width):
            new_image[i, j] = np.max(input[i:i + pool_size, j:j + pool_size])
    return new_image.astype(np.int32)


def flatten(input):
    return input.flatten()

def dense(input, weights, bias):
    return np.dot(weights, input) + bias

def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

def train_cnn(input, kernel, pool_size, stride):
    conv_output = convolve2d(input, kernel, stride)
    relu_output = relu(conv_output)
    print("Convolution Output: \n", relu_output)
    plt.imshow(relu_output, cmap='gray')
    plt.title("Convolution Output")
    plt.show()

    pool_output = maxpooling(relu_output, pool_size, stride)
    print("Max Pooling Output: \n", pool_output)
    plt.imshow(pool_output, cmap='gray')
    plt.title("Max Pooling Output")
    plt.show()

    flatten_output = flatten(pool_output)
    print("Flatten Output: \n", flatten_output)
    plt.imshow(flatten_output.reshape(1, -1), cmap='gray')
    plt.title("Flatten Output")
    plt.show()

    weights = np.random.rand(flatten_output.size)
    bias = np.random.rand(1)
    dense_output = dense(flatten_output, weights, bias)
    print("Dense Layer Output: \n", dense_output)
    plt.imshow(dense_output.reshape(1, -1), cmap='gray')
    plt.title("Dense Layer Output")
    plt.show()

    sigmoid_output = sigmoid(dense_output)
    return sigmoid_output
pool_size = 2
stride = 1
input = np.random.randint(0, 255, (9, 9)).astype(np.int32)
kernel = np.array([[1, 3, 1], 
                   [2, 0, 0], 
                   [-1, 1, -2]])
# [[-1, 0, 1],
#  [-1, 0, 1],
#  [-1, 0 ,1]]
print("Input Image: \n", input)
print("Kernel: \n", kernel)
plt.imshow(input, cmap='gray')
plt.title("Input Image")
plt.axis('off')
plt.show()
sigmoid_output = train_cnn(input, kernel, pool_size, stride)
print("sigmoid Output: ", sigmoid_output)


In [ ]:
# Load MNIST dataset
data = mnist.load_data()
(x_train, y_train), (x_test, y_test) = data
x_train = x_train.reshape((x_train.shape[0], 28, 28, 1)).astype('float32') / 255
x_test = x_test.reshape((x_test.shape[0], 28, 28, 1)).astype('float32') / 255

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

Epoch 1/5


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8997 - loss: 0.3275 - val_accuracy: 0.9788 - val_loss: 0.0741
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9818 - loss: 0.0597 - val_accuracy: 0.9799 - val_loss: 0.0694
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9895 - loss: 0.0339 - val_accuracy: 0.9848 - val_loss: 0.0518
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9923 - loss: 0.0244 - val_accuracy: 0.9854 - val_loss: 0.0532
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.9962 - loss: 0.0136 - val_accuracy: 0.9858 - val_loss: 0.0550
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9804 - loss: 0.0608
Test accuracy: 0.9847999811172485


In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_1 (Conv2D)               │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 5408)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │       692,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,081,888 (7.94 MB)

 Trainable params: 693,962 (2.65 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,387,926 (5.29 MB)

In [ ]:
y_pred = model.predict(x_test)
predicted_classes = np.argmax(y_pred, axis=1)
print("Predicted classes: ", predicted_classes)
print("True classes: ", y_test)

## Experiment 4

In [11]:
# Experiment 4: RNN

input_sentences = [
    "I love programming",
    "Python is great",
    "I enjoy learning new things",
    "TensorFlow is a powerful library",
    "Deep learning is fascinating"
]

def one_hot_encode(sentences):
    tokens = [word_tokenize(sentence.lower()) for sentence in sentences]
    vocab = set(word for sentence in tokens for word in sentence)
    print(len(vocab))
    word_to_index = {word: i for i, word in enumerate(vocab)}
    encoded = []
    for sentence in tokens:
        encoded_sentence = np.zeros(len(vocab))
        for word in sentence:
            encoded_sentence[word_to_index[word]] = 1
        encoded.append(encoded_sentence)
    return np.array(encoded)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def SimpleRNN(input):
    embeddings = one_hot_encode(input)

    input_size = embeddings.shape[1]
    hidden_size = 20
    output_size = 1
    weights_input = np.random.rand(input_size, hidden_size)
    weights_hidden = np.random.rand(hidden_size, hidden_size)
    weights_output = np.random.rand(hidden_size, output_size)
    biases_hidden = np.random.rand(hidden_size)
    biases_output = np.random.rand(output_size)
    hidden_state = np.zeros(hidden_size)
    outputs = []

    for t in embeddings:
        hidden_state = np.tanh(np.dot(t, weights_input) + np.dot(hidden_state, weights_hidden) + biases_hidden)
        output = sigmoid(np.dot(hidden_state, weights_output) + biases_output)
        outputs.append(output)
    return np.array(outputs)

rnn_output = SimpleRNN(input_sentences)
print("RNN Output: \n", rnn_output)

16
RNN Output: 
 [[0.99989174]
 [0.99992822]
 [0.99992822]
 [0.99992822]
 [0.99992822]]


In [ ]:
from keras.datasets import imdb
from keras.preprocessing import sequence

data = imdb.load_data(num_words=1000)
(x_train, y_train),(x_test, y_test) = data

model = Sequential()
model.add(layers.Embedding(input_dim=1000, output_dim=64))
model.add(layers.SimpleRNN(128))
model.add(layers.Dense(10, activation='sigmoid'))
model.add(layers.Dense(2, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
x_train = sequence.pad_sequences(x_train, maxlen=500)
x_test = sequence.pad_sequences(x_test, maxlen=500)
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

Epoch 1/5
625/625 ━━━━━━━━━━━━━━━━━━━━ 38s 60ms/step - accuracy: 0.5058 - loss: 0.6953 - val_accuracy: 0.5586 - val_loss: 0.6907
Epoch 2/5
625/625 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5427 - loss: 0.6852

In [ ]:
y_pred = model.predict(x_test)
predicted_classes = np.argmax(y_pred, axis=1)
print("Predicted classes: ", predicted_classes)
print("True classes: ", y_test)
print(x_test[0], predicted_cl

## Experiment 5

In [46]:
def distance(input, weights):
    sum = 0
    for i, w in zip(input, weights):
        sum += np.pow(i - w, 2)
    return sum

def som(x, w):
    min_dist = min(distance(x, w.T[0]), distance(x, w.T[1]))

    
    return min_dist

x = [1, 0, 1, 0]
w = np.array(
    [[0.2, 0.8],
     [0.6, 0.4],
     [0.5, 0.7],
     [0.9, 0.3]]
)

som(x, w)

np.float64(0.38)

In [51]:
# Simple 2D data (e.g. clusters)
data = np.random.rand(100, 2)  # 100 2D points between 0 and 1

grid_size = (10, 10)
som_weights = np.random.rand(grid_size[0], grid_size[1], 2)  # (10x10 grid with 2D weight vectors)

def train_som(data, weights, num_epochs=100, learning_rate=0.1, radius=2):
    grid_x, grid_y, input_dim = weights.shape
    
    for epoch in range(num_epochs):
        for input_vector in data:
            # 1. Find Best Matching Unit (BMU)
            diff = weights - input_vector
            dist = np.linalg.norm(diff, axis=2)
            bmu_idx = np.unravel_index(np.argmin(dist), (grid_x, grid_y))
            
            # 2. Update BMU and its neighbors
            for i in range(grid_x):
                for j in range(grid_y):
                    # Compute neighborhood function (Gaussian)
                    distance_to_bmu = np.linalg.norm(np.array([i, j]) - np.array(bmu_idx))
                    if distance_to_bmu <= radius:
                        influence = np.exp(-distance_to_bmu**2 / (2 * (radius**2)))
                        weights[i, j] += learning_rate * influence * (input_vector - weights[i, j])
    return weights

trained_weights = train_som(data, som_weights)

# Plot input data
plt.scatter(data[:, 0], data[:, 1], c='gray', label='Data')

# Plot neuron weights
for i in range(grid_size[0]):
    for j in range(grid_size[1]):
        w = trained_weights[i, j]
        plt.plot(w[0], w[1], 'ro')  # plot neuron
plt.title("SOM Mapping")
plt.legend()
plt.show()

[[[0.03754541 0.75417621]
  [0.06243721 0.70862715]
  [0.09151505 0.59479407]
  [0.13316265 0.54653364]
  [0.13951154 0.49315309]
  [0.18195957 0.41418339]
  [0.15103886 0.35789744]
  [0.13525367 0.30800238]
  [0.13368453 0.27206507]
  [0.1034411  0.22077095]]

 [[0.06795013 0.81370199]
  [0.06586271 0.7241955 ]
  [0.11192073 0.66532842]
  [0.15738638 0.57003077]
  [0.22605298 0.50709606]
  [0.20728046 0.43193992]
  [0.25557086 0.36616791]
  [0.18262342 0.28846613]
  [0.14850224 0.2112611 ]
  [0.13400217 0.18250384]]

 [[0.12506835 0.83333662]
  [0.12108477 0.78646578]
  [0.18720945 0.63083588]
  [0.2603896  0.56811517]
  [0.30120969 0.50363199]
  [0.35540615 0.42206597]
  [0.35840022 0.32758918]
  [0.31639241 0.25682901]
  [0.21422673 0.15694134]
  [0.20756642 0.10922378]]

 [[0.17445615 0.8279782 ]
  [0.25113351 0.76362549]
  [0.28008676 0.65214336]
  [0.35052004 0.56677479]
  [0.37779209 0.46339596]
  [0.43920733 0.40506416]
  [0.42303317 0.33690224]
  [0.38709743 0.27101099]
  [0.3

## Experiment 6

In [79]:
from sklearn.decomposition import PCA

def circle(r, θ):
    x = r * np.cos(θ)
    y = r * np.sin(θ)
    return x, y

def data_generated():
    train = []
    for i in range(1000):
        θ = np.random.uniform(0, 2*np.pi)
        r = np.random.randn()
        x, y = (circle(r, θ))
        train.append([x, y])
    return np.array(train)

def PCA_train(train):
    scale = StandardScaler()
    scaled_train = scale.fit_transform(train)
    pca = PCA(n_components=1)
    train_pca = pca.fit_transform(scaled_train)
    inversed = pca.inverse_transform(train_pca)

    mse = ((train - inversed) ** 2).mean(axis=None)
    return mse

def tanh(x):
    return np.tanh(x)

def encoder(data, weights, bias):
    return tanh(np.dot(data, weights) + bias)

def decoder(data, weights, bias):
    return tanh(np.dot(data, weights) + bias)

def autoencoders(encoder, decoder, data):
    input_dim = data.shape[1]
    latent_dim = 1
    
    weight_encoder = np.random.randn(input_dim, latent_dim)
    bias_encoder = np.random.randn(latent_dim)
    weight_decoder = np.random.randn(latent_dim, input_dim)
    bias_decoder = np.random.randn(input_dim)

    z1 = encoder(data, weight_encoder, bias_encoder)
    z2 = decoder(z1, weight_decoder, bias_decoder)

    mse = ((data - z2)** 2).mean()
    return mse

train = data_generated()

ae = autoencoders(encoder, decoder, train)
pca = PCA_train(train)

print("Autoencoders: ", ae)
print("PCA: ", pca)


Autoencoders:  0.8521993796328488
PCA:  0.30546557481665276
