In [19]:
import numpy as np 
import pandas as pd 
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [20]:
inputs = [
    "I love this product",
    "This product is the best",
    "It is a fantastic product",
    "This is a bad product",
]

In [21]:
def Embedding(inputs):
    tokenized_sequences = [word_tokenize(sentence.lower()) for sentence in inputs]

    all_words = sorted(set(word for seq in tokenized_sequences for word in seq))
    word_to_index = {word: i for i, word in enumerate(all_words, start=0)}  
    vocab_size = len(word_to_index)  

    one_hot_encoded = []
    for seq in tokenized_sequences:
        sentence_vector = np.zeros(vocab_size) 
        for word in seq:
            if word in word_to_index:
                index = word_to_index[word]
                sentence_vector[index] = 1  
        one_hot_encoded.append(sentence_vector)



    return one_hot_encoded

sentence_embeddings = Embedding(inputs)
print("\nFinal Sentence Embeddings:\n", sentence_embeddings)


Final Sentence Embeddings:
 [array([0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1.]), array([0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1.]), array([1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.]), array([1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.])]


In [22]:
sentence_embeddings


[array([0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1.]),
 array([0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1.]),
 array([1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.]),
 array([1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.])]

In [23]:
def SimpleRNN(inputs):
    sentence_embeddings = Embedding(inputs)
    sentence_embeddings = np.array(sentence_embeddings)
    print("Sentence Embeddings Shape:", sentence_embeddings.shape)

    input_size = sentence_embeddings.shape[1]  # dynamically get input size
    hidden_size = 3
    output_size = 3

    # Create RNN weights
    W = np.random.rand(hidden_size, input_size)  # (3, input_size)
    U = np.random.rand(hidden_size, hidden_size)  # (3, 3)
    V = np.random.rand(output_size, hidden_size)  # (3, 3)

    h = np.zeros(hidden_size)
    y = []

    for s in sentence_embeddings:
        h = np.tanh(np.dot(W, s) + np.dot(U, h))  # (3,)
        o = np.dot(V, h)  # (3,)
        y.append(o)

    return y

In [24]:
sentence_embeddings = Embedding(inputs)
sentence_embeddings

[array([0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1.]),
 array([0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1.]),
 array([1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.]),
 array([1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.])]

In [25]:
output = SimpleRNN(inputs)

Sentence Embeddings Shape: (4, 11)


In [17]:
output

[array([0.32693828, 2.11080631, 1.48054214]),
 array([0.3444898 , 2.27576716, 1.58157489]),
 array([0.34471151, 2.27366483, 1.57912069]),
 array([0.34447979, 2.27293131, 1.57844277])]